<a href="https://colab.research.google.com/github/SakshiMaholiya123/Machine-Learning/blob/linear_algebra/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
file=pd.read_csv('hdfc_loan_dataset_full_enriched - hdfc_loan_dataset_full_enriched.csv')

In [ ]:
file.head()

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,...,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper

In [ ]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 47 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Loan_ID                      1000 non-null   object
 1   Bank                         1000 non-null   object
 2   Customer_Name                1000 non-null   object
 3   Gender                       1000 non-null   object
 4   Married                      1000 non-null   object
 5   Dependents                   1000 non-null   int64
 6   Education                    1000 non-null   object
 7   Employment_Status            1000 non-null   object
 8   Applicant_Income             1000 non-null   int64
 9   Coapplicant_Income           1000 non-null   int64
 10  Loan_Amount                  1000 non-null   int64
 11  Loan_Term_Months             1000 non-null   int64
 12  Credit_History               1000 non-null   int64
 13  Property_Area                1000 non-null   object
 14  Age                          1000 non-null   int64
 15  Loan_Status                  1000 non-null   object
 16  CIBIL_Score                  1000 non-null   int64
 17  Annual_Household_Income      1000 non-null   int64
 18  Debt_to_Income_Ratio         1000 non-null   float64
 19  Purpose_of_Loan              1000 non-null   object
 20  Existing_EMIs                1000 non-null   int64
 21  Number_of_Previous_Loans     1000 non-null   int64
 22  Default_History_Count        1000 non-null   int64
 23  Employment_Length_Years      1000 non-null   int64
 24  Business_Type                201 non-null    object
 25  Asset_Value                  1000 non-null   int64
 26  Guarantor                    1000 non-null   object
 27  Co-signer_Relationship       766 non-null    object
 28  Monthly_Expense              1000 non-null   int64
 29  Organization_Type            1000 non-null   object
 30  Region_Branch                1000 non-null   object
 31  Mobile_Verified              1000 non-null   object
 32  Email_Verified               1000 non-null   object
 33  Institutional_Relationships  1000 non-null   object
 34  Application_Text             1000 non-null   object
 35  Customer_Feedback            1000 non-null   object
 36  Agent_Notes                  1000 non-null   object
 37  Loan_to_Annual_Income        1000 non-null   float64
 38  Customer_Sentiment           1000 non-null   object
 39  Religion                     1000 non-null   object
 40  State                        1000 non-null   object
 41  City                         1000 non-null   object
 42  PIN_Code                     1000 non-null   int64
 43  Aadhaar_Synthetic            1000 non-null   float64
 44  Phone_Number                 1000 non-null   int64
 45  Email                        1000 non-null   object
 46  Occupation                   1000 non-null   object
dtypes: float64(3), int64(17), object(27)
memory usage: 367.3+ KB

In [ ]:
column = [
    'Applicant_Income','Coapplicant_Income','Loan_Amount','Loan_Term_Months',
    'Credit_History','Age','CIBIL_Score','Annual_Household_Income','Debt_to_Income_Ratio',
    'Existing_EMIs','Number_of_Previous_Loans','Default_History_Count',
    'Employment_Length_Years','Asset_Value','Monthly_Expense','Loan_to_Annual_Income'
]

In [ ]:
df=file[column]

In [ ]:
df

,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Term_Months,Credit_History,Age,CIBIL_Score,Annual_Household_Income,Debt_to_Income_Ratio,Existing_EMIs,Number_of_Previous_Loans,Default_History_Count,Employment_Length_Years,Asset_Value,Monthly_Expense,Loan_to_Annual_Income
0,56976,0,8031545,360,1,36,699,683712,0.098,5610,0,0,1,744861,30391,11.747
1,1856,0,899361,240,1,42,707,22272,4.939,9166,1,0,0,0,1856,40.381
2,64553,0,2387748,60,1,38,641,774636,0.000,0,2,0,1,2913766,24557,3.082
3,88450,0,658856,12,1,32,677,1061400,0.301,26613,1,0,3,3488244,36750,0.621
4,9539,0,198671,36,0,35,594,114468,0.000,0,0,0,2,472179,3920,1.736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44713,0,5883603,360,1,35,707,536556,0.116,5165,1,0,2,1895538,11899,10.965
996,70886,0,2780228,300,0,37,561,850632,0.284,20102,1,0,1,2413969,32458,3.268
997,24392,11337,301249,24,1,28,725,428748,0.966,34514,2,0,0,1631635,22977,0.703
998,64803,94136,719891,48,1,33,679,1907268,0.214,34000,1,0,4,5000832,72376,0.377
999,22938,0,61019,120,1,24,690,275256,0.664,15226,0,0,0,0,16105,0.222

In [ ]:
mat=np.array(df)

In [ ]:
mat

array([[5.697600e+04, 0.000000e+00, 8.031545e+06, ..., 7.448610e+05,
        3.039100e+04, 1.174700e+01],
       [1.856000e+03, 0.000000e+00, 8.993610e+05, ..., 0.000000e+00,
        1.856000e+03, 4.038100e+01],
       [6.455300e+04, 0.000000e+00, 2.387748e+06, ..., 2.913766e+06,
        2.455700e+04, 3.082000e+00],
       ...,
       [2.439200e+04, 1.133700e+04, 3.012490e+05, ..., 1.631635e+06,
        2.297700e+04, 7.030000e-01],
       [6.480300e+04, 9.413600e+04, 7.198910e+05, ..., 5.000832e+06,
        7.237600e+04, 3.770000e-01],
       [2.293800e+04, 0.000000e+00, 6.101900e+04, ..., 0.000000e+00,
        1.610500e+04, 2.220000e-01]])

average of the applicant income column

In [ ]:
average_applicant=np.mean(mat[:,0])

In [ ]:
print(average_applicant)

42430.057

Find max value from Loan_Amount column.

In [ ]:
max_value=df['Loan_Amount'].max()

In [ ]:
print('maximum value present in the loan amout is ',max_value)

maximum value present in the loan amout is  13790960

using numpy

In [ ]:
maximum_value=np.max(mat[:,2])

In [ ]:
print(maximum_value)

13790960.0

vector addition
adding applicant income and co applicant income

In [ ]:
applicant_income=np.array(df['Applicant_Income'])
Coapplicant_income=np.array(df['Coapplicant_Income'])
total=applicant_income+Coapplicant_income
total

array([ 56976,   1856,  64553,  88450,   9539,  39184,  81223,      0,
        17675,  71409,  46972,  38126,  63115,  35034,  53684, 113545,
        29319,  10609,  66474,  95054,  48611,  15509, 117255,  97735,
        45050,  34900,   9381,   3000,  54597,  43481, 143023,  42416,
        92535,  39270,  55899,  33527,  28605,  33983,  23543, 129184,
         3000,  60010,  42393,  48860,  66608,  27205,  52863,  53000,
        91498,  47655,  92893,   1519,  80579,  94207,  55058,  23796,
        33925,  31372, 212945,  39035, 135891,  33478,  46668,  45832,
       136339,  29274,  89323,  66933,  36203,  52935,  33160,   9768,
        85714, 119391,  21455,  36438,  40206,  38127,  12104,      0,
        71887, 112111,   5000,   3000,  28345,   7914,  89966, 101852,
        13318,  80548,  62827,   3884,  21109,  45652,  60198,  13049,
        99076,  99781,  83511,   4812,  82923, 157182,  32371,  13956,
        86493, 108790, 101761,  98367,   7781, 144852,  79239,  92625,
         3000, 131749,   5889,  49808,  78237, 149266,  57893, 121928,
         3000,  31167,   6348,  70367,  16663,  39715,  47474,   8343,
        25098,  88024,  64266,  18689,  22330,  12751,  55766,  60739,
         9321,  70840,  37434,  26101,  26186,  52574,   3000, 174550,
        33075,  90515,  79125,  44700,  69520, 196030,  54662,  29035,
       115050,  82034, 184168,  53917,  75210,  25232,   3345,  23065,
        58019,  25214,  17204,  31741,  46804,  37976,   9510,  71452,
         5936,  78039,  55550,  78276,   9289,   5000,  39066,  60452,
        89928,  26576, 114065,  35554,  39521,  67404,  56580,  56562,
         8522,  74437,  75000,  28635,  25438,  34328,  39818,  67152,
        16035, 116683,  40747,  89015,  45529, 119153,  77648, 135687,
        45852,  82095,   9539,  27179,   3000,  43892,  52605,  64018,
        65997,  86670,  98231,  69719,  24431, 123802,  67738,  59497,
        20634,  56031,  41652,  68598,  63646,  40668,  44827, 110433,
        53622,  41934, 104492,  68466,  71067,   3000,  55041,  98872,
        68665,  85104,  96373, 112331,  82090,  25958,  24326,  47907,
        43013,  43529,  27044,  54125,  16686,  48928,  57935,  54201,
        30418,  73428,  75757,  25044,  35211,  30714,  34810,  87030,
        40922,   5120,  91076,  14238,  15584,  59470,   6362, 120213,
        47615,   6028,  54286,  51235,  45941,   5000,  25798,  36122,
        58076,      0,  15141,  30953,   7230,  56752,      0,  19357,
       108873,  25418,  30636, 148702,  84800,  19830,   6877,   3423,
        73489,  97012,      0,   5036,  54882,  64835,  86422,  53243,
        42283,  35348,  19248,  11426,   4003,  45015,  36691,  31483,
        12347,  25159,  80767,   4930, 115141,  54674,  62190,  41951,
        49582,  53584,  75078,  47133,  77753,  68088,  12412,  24306,
        16217,  28340,  14671,  13730,  22082,  49714,   8017,  32402,
        24982,  90164,  62031,  15020,  60014,  20054, 121113,  55140,
        53422,  24196,  71901,  49250,  81622,  68331,  77543,  94363,
        38159,      0,  19274,  40421,  40475,  99589,   3805,   8429,
        78837,  56692,   3000,  15176,  30038,   3000,  14348,   3000,
        46175,  12088,  42038,   5065,  12895,  18498,  20219,  79030,
        43508, 120405,  47814,  84400, 109092, 134441,  53719, 147673,
        26394,  34732,  20404,   9255,  64941,  94275,  21150,  98157,
        61556,  18182,  56676,  45176,  79902,  61141,  89800, 131129,
         3000,  75390,  93704, 151888,  75547,  92795,  19389, 111991,
         7866,  62859,  80153,  69245,  56495,   5737,  66708,  35458,
        54718,  42178,  88202,  30575,   5000,  32611,   6686,      0,
        44786,  36809,  35983,  69783,   3867,  92230,  48939,  48033,
        74680,  26860,  69020,  66993,  25547,  55894,  70195,      0,
        89759,  59710, 103651,  63686,  46995,  68940,  62580,   5920,
        51486,  75177,  16768,  13725,  58929,   3537,   3811,   2428,
        11317,  53495,  11029,   8375,  58108,  38787, 142321,  43457,
        56701,  41995,   7918,  14933,  37771,  37976, 195649,  51616,
       132207,  50217,      0,  44435, 100864, 125692,  77437,  15602,
       120034,  45933,  34788, 171824,  54139,   3000,  50257,   2713,
        81288,  14831,    272,  22834,  42106,   3000,  95267,  52159,
        86521,  48690,  86338,   3000,  34018,  66095,  56407,   6757,
       102006, 142655,  14147,   7908,  40422,  48363,  48907,  12151,
         7986,  59545, 168570,  84244,  47412,  75261,  12793,   5000,
       129363,  55914,  20226,  52222,  59945,  44031, 189154,  59208,
         5000,   6537,  19185,  45095,   8925,  61095,  33599, 113398,
        41843,  23964,  63440,  20617,  32059,   5883,  29171,  46933,
        76177,   3229,   5000,  56949,  48627,  39608,  43156,  64772,
        71369,  62037,   3000,  40076,  26877,  78279,  60349, 154257,
        18143,  72724,  10849,  45888,  65575, 106999,  32857, 195607,
        38642,  68975,  19809,  74344, 107520,  47514,   4616,  19490,
         9930,  30757,  25533,  90536,   3000,  72657,  45453,  12244,
        82476,  82795,  53395,   7171,   9252,  38928,  11129,  61964,
        17513,  24233,  65247,  49909, 153840,  60583,  31981,  27670,
        42404,  51992,  72699,   9403,  44307,  33233,  34645, 107782,
       104372,  51570,   3000, 139027,  33360,   5723,  26138, 133054,
       120584,  53961,   5000,   5631,  23755,  22266,  64581,  50729,
        61018,   3000,  57085,  68162,  30644,  38936,  76194,  20684,
        21341,  21753, 118010,  10534,  37382,   9241,  76122,  54115,
        43673,  64803, 103233,  60033,  79441,  77797,  48523,   8582,
        14562,  58378,  85836,  57295,  53093,  46855,  57521, 101807,
         3000,  11129,  44988,  79450,  85676,  23223,  65529,  34792,
         5000,  67110,  34849,  60489,  13958,   3000,  70149,  54248,
        12797,  28185,  94591,  66393,  11864,  35933, 138549,  62598,
        12599,  80026,  56586, 103176,  85359,  74998, 203554,   5000,
        90499, 105849,   3000,   3000,  37128,  53357,   9931,  62873,
        48262, 106553,  68419, 162659,  82246, 160789,  78409,   8321,
         4028,   5000, 110358,   1911,   6602,  22211,  28455,  77996,
        30000,  60282,  68302,  16064,  96967,  35588,  30652,  10540,
        31813,   3902,  15174,  70996,  50871,  17622, 105075,  42713,
        45583,  50430,  28390,  78566,   3000,      0,  54948,   3000,
        71637,  50050,  51809, 102350, 138603,  44822, 112722,   3000,
        43256,  67156,  48029,  28009, 138610,  27230,  66878,  69593,
         7721, 127636,  45273,  48104,  39561,  26072,  24759,  47315,
        12826,  39467,  33973,  22257,  97389,  51826,  65320, 108555,
        39412,  35114,  60413,  58890,  69658,  37868,  89011,  60874,
         9427,  27464,  54965,  26866,  59584,  38921,  13432,   3000,
       106490,  85094,  70799,  30865,  89926,  70946, 136700,  40563,
       167582,  23344,  64993,  24628,  38524,  40082,   6848,  42026,
        55496,  14333,   5000,  33195,  58603,  18321,  22773,  59322,
        66471,   9614,  65714,  25447,  24204,  56322,  15603,  27580,
        11552,  48780, 116843,  44877, 157969,  42961,  13013, 126560,
        47459,  16261,  13714,  31559,   5648,  61964,  77815,  75255,
        47136,  45864,  13692,  21740,  39294,  26018, 136100,  81210,
        79206,  31574, 178963,  10667,  51930,  39222,   5719,  13514,
        67059,   8275,  52590,  46270, 145019,  57177,  69834,  38514,
       125346,  47829, 120569,   7533,  57236, 127237,  43152,  60475,
       105782,  97964,  18263,   3343,  86867,  94213,  33336,  30265,
        62415,  66977,   3727,  38919,  22077,  59358,      0, 154844,
        43248,   9265,  51832,   3570,  38591,  43309,  33435, 171514,
        44059,  36218,  87095,  45658, 141206,  85105,  34903,   4891,
       128614,  81148, 158875,  46562,  42143,   3529,  12493,  68684,
        33645,   6710,  67816,  45957,  12700,  20877,  38875,  88212,
         6976,   9649,  68112,  69866,  25258,   5736,   6334,  46522,
         4322,  33942,  72893,   5176,  57876,  27673,  64925,  12511,
        89726, 131596,  43497,  58157,  15573,  19185,  30612,  53893,
        41349,  74560,  59901, 110914,   7762,  15968,  80592,  27515,
        25503,  29134, 153955,  29060,   8899,  97402,  35040,  58544,
        54261,  16916,  86710,  25845,  18399, 138533,  55486,  11649,
        63883, 107061,  36719, 180892,  67355,   7943,  10823,  16302,
         3000,  83038,   4802,  17231, 157888,  19396, 198978,  67489,
        35440,  82977,   7539,   3177,  64203,  80625,  31279,  23344,
        42404,  49540,  20590,  66447,  63088,  27598,  57507,  77767,
        22599, 124758,  64907,  42003,  32975, 120595,  13966,  92447,
        59313,  42145,  58010,  44713,  70886,  35729, 158939,  22938])

vector subtraction

In [ ]:
expense=np.array(df['Monthly_Expense'])

In [ ]:
savings=total-expense
savings

array([ 26585,      0,  39996,  51700,   5619,  21411,  44078,      0,
         6020,  45192,  35961,  11610,  37146,  20899,  20675,  66848,
        19635,   8609,  41242,  45608,  23656,  12432,  59418,  47545,
        29897,  28549,   7287,      0,  38303,  17167,  87206,  33739,
        48197,  17477,  19230,  16207,  16715,  19916,   6978,  75256,
            0,  30413,  22098,  24590,  32924,  13586,  31722,  22566,
        45901,  28549,  50633,      0,  51629,  53078,  31002,  11539,
        24163,  20933, 119874,  14904,  68647,  19997,  31859,  25823,
        76530,  10424,  46010,  38252,  19929,  28410,  13807,   3905,
        38294,  60474,  10887,  21560,  26064,  27539,      0,      0,
        43251,  68376,      0,   1000,  21045,   4321,  44171,  58858,
        11318,  41852,  24008,      0,  11657,  22359,  34710,   8093,
        60894,  58191,  45008,   2812,  46377,  90470,  19387,   2141,
        52562,  76769,  60283,  53279,   4096,  84704,  33755,  42385,
         1000,  68924,   1368,  16213,  37664,  82432,  36432,  77430,
         1000,  25899,      0,  37731,  12497,  14341,  42735,   5688,
        16986,  47306,  34856,   2916,   4888,  10751,  31002,  33730,
         1749,  35499,  25917,  16049,  23059,  36204,   1000,  98661,
        21477,  57744,  42136,  25891,  41845, 102005,  22147,  18541,
        71175,  39412, 103984,  30748,  44005,   7481,    147,  17133,
        38025,  18476,   2517,  20393,  19085,  20524,      0,  37432,
         3936,  40564,  36065,  37752,   7289,   3000,  21508,  36959,
        49973,  12476,  56283,  20529,  20744,  40810,  31574,  32918,
         5348,  45792,  33155,  17961,  23438,  28178,  22789,  27141,
         7804,  74702,  18638,  56430,  21186,  72496,  44404,  71645,
        19746,  41828,   5595,   9497,      0,  25637,  28443,  41066,
        50460,  44876,  58028,  31906,  17502,  67519,  36513,  30293,
        15639,  25928,  26839,  37741,  39839,  14345,  19742,  60501,
        26659,  22288,  56194,  39605,  44020,   1000,  31310,  53118,
        43417,  43474,  52479,  52608,  52785,  22292,  11001,  28938,
        25032,  30332,  13323,  39233,   3033,  23509,  33732,  31821,
        20157,  31940,  50390,  13811,  17658,   6470,  22504,  52401,
        23032,   3120,  49515,   3495,      0,  25499,   4362,  59977,
        33143,    787,  33042,  36514,  23638,   3000,  13500,  25090,
        20337,      0,   7428,  20915,   5230,  35634,      0,  13030,
        53218,   8422,  18057,  89856,  46866,    178,   4877,   1423,
        43836,  49436,      0,   1370,  36302,  32774,  52799,  36191,
        25195,  31334,  12159,   4078,   2003,  30557,  23033,  14725,
         8739,  17327,  42017,      0,  67251,  29991,  30538,  26090,
        26660,  29545,  47412,  27166,  44836,  30462,   6562,  18371,
         6605,  21095,   9067,   3169,  17368,  25160,      0,   9975,
         9393,  45333,  25478,      0,  39158,  12793,  70611,  26061,
        32860,  10363,  38002,  32517,  40973,  30057,  48255,  59037,
        21998,      0,  10547,  21905,  19590,  58754,   1805,   6429,
        41508,  30036,   1000,   6900,  16222,   1000,   3550,      0,
        15381,   1511,  20920,   3065,   6331,  13845,  18219,  50098,
        15279,  81807,  24590,  46714,  58833,  74743,  27966,  74856,
        13348,  23145,   4980,   3363,  40105,  57073,  10700,  48115,
        34474,  12296,  34595,  22591,  37578,  33086,  53761,  81524,
          423,  35754,  54985,  76825,  44121,  45510,  13861,  61713,
            0,  36390,  48444,  38229,  40543,   3731,  36294,  14393,
        25929,  19945,  42512,  12811,   3000,  17992,   4686,      0,
        13674,  21794,  19074,  38732,      0,  53720,  28664,  27052,
        41419,  14350,  43906,  33117,  16857,  24859,  32927,      0,
        49828,  30417,  54735,  42575,  24043,  36060,  28263,      0,
        35618,  43914,   8889,   9413,  33904,      0,   1811,      0,
         3937,  30562,      0,   6375,  41126,  13715,  70187,  26337,
        35655,  17322,    839,  12475,  20202,  22918, 107479,  23066,
        75856,  23709,      0,  23472,  54542,  67989,  39028,   2080,
        71658,  23792,  26771,  94051,  31071,      0,  31020,      0,
        38979,  12050,      0,   6748,  29758,   1000,  56386,  25389,
        49265,  33115,  41959,      0,  18603,  29998,  30943,   2590,
        56769,  82143,  11544,   5908,  21102,  20161,  23338,   9025,
         5986,  27657,  90457,  52421,  31517,  39596,   5298,   3000,
        71453,  31813,  14276,  29109,  38464,  17690,  98382,  26339,
         3000,   4537,   8697,  21275,   2752,  37441,  21238,  49548,
        22501,  16895,  39009,  13620,  12635,      0,   8324,  22606,
        49728,      0,      0,  37009,  25919,  22463,  26281,  21831,
        43119,  33364,      0,  21743,   9151,  52581,  37373,  90326,
        10360,  43796,   8787,  31346,  31136,  55647,   8337, 114833,
        23256,  29873,   8721,  38745,  56463,  17195,   2616,  17490,
         2023,  16185,   9056,  49302,      0,  37887,  28057,      0,
        45684,  41411,  29057,   3855,   5030,  26284,   9129,  33166,
        15513,   8063,  29354,  29382,  85156,  27215,  21391,  19839,
        22050,  30014,  34433,   5064,  24770,  18202,  12709,  57116,
        53664,  17812,   1000,  73112,  20962,   3723,  12168,  72741,
        72572,  32256,      0,   3631,   6934,   5702,  39354,  31158,
        35992,   1000,  36343,  33216,  16875,  25314,  37639,  10036,
            0,   8044,  61351,   7580,  31635,   3382,  39049,  25462,
        27789,  27122,  43981,  40717,  47516,  39490,  25489,      0,
         8706,  34696,  47750,  30293,  28337,  29066,  33686,  67279,
         1000,   9129,  27124,  42889,  41808,  12185,  31772,  11335,
         2151,  36515,  22960,  31864,   5872,      0,  33961,  25358,
         9645,  18847,  50995,  36455,   9589,  19485,  75709,  35554,
        10599,  39195,  33824,  47845,  50133,  43155, 105792,   3000,
        49631,  55434,   1000,   1000,  24196,  30259,      0,  38100,
        31147,  51063,  37659,  93861,  41261,  95573,  41820,   6321,
         2028,      0,  59126,      0,   4602,  15481,  19772,  45493,
        11922,  32025,  42521,   5492,  58351,  14755,  18586,      0,
        12144,      0,    214,  45255,  25414,  15040,  55695,  25106,
        29974,  28725,  23439,  40450,      0,      0,  34373,      0,
        37064,  26057,  26273,  55485,  74941,  19060,  58418,   1000,
        24187,  40415,  22250,   8123,  73130,  19284,  31358,  41447,
            0,  67801,  28186,  22391,  19751,  17427,  13021,  23751,
         6880,  18174,  11988,  20257,  47596,  22952,  35425,  69638,
        12550,  19537,  31709,  37581,  36781,  21344,  57898,  33625,
         1717,  19121,  34662,  16300,  31911,  25873,   8283,      0,
        45247,  43772,  40017,  16791,  55565,  40497,  80544,  20575,
        89992,  18424,  33307,   7872,  22449,  27396,      0,  20943,
        37215,   8514,   3000,  18325,  37419,  16321,  15469,  35248,
        37049,   7614,  34690,  14001,  13426,  29835,  11343,   9643,
            0,  19643,  63369,  30086,  90361,  21412,   4118,  64509,
        26796,  14076,  11714,  20458,   3648,  39601,  41743,  45523,
        21680,  25456,    917,  11474,  15631,   9288,  70497,  38778,
        52479,  14562,  95212,      0,  21112,  18102,   3719,  11514,
        40127,   6275,  22256,  30119,  78292,  24277,  36955,  24572,
        70000,  28806,  65424,   1060,  33331,  70145,  22102,  34205,
        53725,  54022,   9397,   1343,  46900,  53653,  15026,  23328,
        24264,  35112,   1727,  24042,  12884,  36505,      0,  88013,
        20359,   7265,  25098,      0,  21103,  26372,  10564,  93597,
        29701,  24738,  44657,  28170,  79217,  40982,  21213,      0,
        67573,  49423,  84978,  31778,  16468,      0,   2059,  30948,
        19445,   4710,  35332,  25885,  10700,   4825,  21905,  52815,
         4976,   5450,  35295,  39753,  10335,      0,      0,  29724,
            0,  21135,  36485,   3176,  32045,  19062,  38559,  10511,
        48586,  68718,  23705,  35550,   1822,  17185,  11659,  35448,
        16347,  38592,  40949,  63373,   3827,   7949,  39159,  10439,
         9974,  11197,  88442,  23934,   6899,  55642,  20008,  25895,
        29043,   7871,  45299,  11369,   9746,  85675,  25337,   7108,
        42397,  64566,  29454,  96265,  37373,   5943,   2849,   7244,
            0,  45971,   2802,    929,  84862,  12621, 113578,  39265,
        29899,  44069,   5539,   1177,  34011,  35722,  24534,  16548,
        22446,  29022,  13191,  40127,  46620,  14581,  37977,  41266,
         9842,  65290,  32789,  22384,  18397,  74975,   9264,  52885,
        28192,  19081,  42152,  32814,  38428,  12752,  86563,   6833])


Get CIBIL score of first customer

In [ ]:
first_cibil=np.array(df['CIBIL_Score'])[0]

Scalar multiplication on applicant income column

In [ ]:
scalar_value=3
scale_res=scalar_value*np.array(df['Applicant_Income'])
scale_res

array([170928,   5568, 193659, 265350,  28617, 117552, 243669,      0,
        53025, 214227,  76659, 114378, 189345,  53880, 161052, 168276,
        87957,  31827, 114810, 129879, 145833,  46527, 169458, 293205,
       135150, 104700,  28143,   9000, 163791, 130443, 269376,  68919,
       277605, 117810, 167697, 100581,  85815, 101949,  70629, 387552,
         9000, 180030,  91518, 146580, 186855,  81615, 158589, 159000,
       274494, 142965, 278679,   4557, 241737, 282621,  82938,  71388,
       101775,  94116, 363528, 117105, 205863,  76851,  90264, 137496,
       244137,  87822, 197160, 200799, 108609, 158805,  45819,  15000,
       159315, 159198,  64365, 109314, 120618, 114381,  36312,      0,
       215661, 336333,  15000,   9000,  85035,  23742, 269898, 305556,
        22821, 187746, 188481,   9000,  63327, 136956, 180594,  26766,
       208845, 299343, 250533,   9000, 248769, 319254,  97113,  41868,
       259479, 224664, 131154, 295101,  23343, 179694, 237717, 277875,
         9000, 262737,  15000, 111870, 234711, 447798, 173679, 271380,
         9000,  82785,  19044, 211101,  39108, 119145, 142422,  25029,
        75294, 264072, 192798,  56067,  56145,  38253,  65232, 182217,
        14673, 189741, 112302,  78303,  78558, 114858,   9000, 249792,
        99225, 271545, 237375, 134100, 208560, 246234, 163986,  87105,
       137589, 246102, 232719, 161751, 159825,  75696,  10035,  69195,
       174057,  32766,  51612,  95223,  88074, 113928,  28530, 114489,
        17808, 168450, 134016, 145506,  27867,  15000,  95364, 181356,
       269784,  39801, 174657, 103047,  86367, 202212, 169740, 153444,
        25566, 223311, 225000,  85905,  54183,  80301,  76113, 201456,
        48105, 192774, 122241, 116160, 106875, 357459, 232944, 224682,
       137556, 246285,  28617,  81537,   9000, 131676, 157815, 127464,
       197991, 260010, 185118, 209157,  73293, 169836, 203214, 178491,
        61902, 168093, 124956, 174351, 147867, 122004, 112341, 153090,
       160866, 125802, 165378, 205398, 213201,   9000, 165123, 196167,
       205995, 255312, 132897, 336993, 246270,  55104,  33444,  66891,
        92118,  67080,  42069,  97542,  50058, 146784, 138420, 162603,
        58560, 121257, 227271,  75132, 105633,  92142, 104430, 150642,
       122766,   9000, 157629,  42714,  46752, 178410,   9000, 289938,
       142845,   9000, 162858, 153705, 137823,  15000,  37620, 108366,
       174228,      0,  45423,  92859,  21690, 138108,      0,  55215,
       164475,  76254,  91908, 227535, 254400,  59490,  20631,  10269,
       220467, 291036,      0,  15108, 113022, 123888, 259266, 159729,
       126849, 106044,  32388,  26709,  12009, 135045,  64725,  94449,
        37041,  75477, 242301,   9000, 151674, 164022, 186570, 125853,
       115509, 105639, 225234, 116133, 233259, 204264,  37236,  72918,
        34125,  55824,  22623,  41190,  66246, 149142,  24051,  97206,
        74946, 270492, 104031,  45060, 180042,  60162, 209115, 165420,
       160266,  38559, 116979, 147750, 244866, 204993, 232629, 164136,
       114477,      0,  57822, 121263, 121425, 145662,   9000,  17376,
       236511, 170076,   9000,  45528,  90114,   9000,  43044,   9000,
       138525,  36264, 126114,  11139,  38685,  32406,  60657, 237090,
       130524, 312543,  67173, 137997, 327276, 403323, 161157, 287469,
        79182, 104196,  36807,  18465, 159018, 282825,  63450, 294471,
       104787,  54546, 170028, 135528, 239706, 183423, 269400, 349584,
         9000, 226170, 166893, 240492, 226641, 278385,  58167, 179301,
        23598, 188577, 152238, 207735, 169485,  17211, 200124, 106374,
       164154, 126534, 154827,  51429,  15000,  97833,   9000,      0,
        96747,  77742,  54753, 209349,   6642, 276690, 120090, 144099,
       122031,  80580, 207060, 200979,  41916, 167682, 210585,      0,
       269277, 179130, 194028, 191058, 140985, 206820, 187740,  15000,
       154458, 225531,  50304,  34656, 176787,   8820,   6909,   7284,
        33951, 160485,  26475,  25125, 174324, 116361, 178320, 130371,
       170103,  69750,  23754,  32814,  77607,  67815, 254886, 154848,
       211845, 150651,      0, 104778, 302592, 150114, 232311,  33456,
       360102, 137799, 104364, 297264, 162417,   9000, 150771,   5130,
       243864,  26118,    627,  50289, 126318,   9000, 285801,  92727,
       209493, 146070, 153810,   9000,  76128, 198285, 100848,  10044,
       245595, 288921,  30447,  23724, 121266, 145089, 146721,  36453,
        23958, 178635, 298914, 252732, 142236, 225783,  38379,  15000,
       178767, 167742,  60678,  67560, 179835,  62868, 345183, 177624,
        15000,  15000,  57555, 135285,  26775, 183285, 100797, 147351,
       125529,  71892, 190320,  61851,  96177,   9336,  87513,  89085,
       228531,   9687,  15000, 162486, 145881, 118824, 129468, 194316,
       214107, 186111,   9000, 120228,  48138, 133281, 181047, 207612,
        31434, 129912,  32547,  91734, 196725, 186924,  76542, 243075,
       115926, 206925,  59427, 223032, 152010, 142542,  10698,  58470,
        29790,  92271,  76599, 182799,   9000, 130890, 136359,  29247,
       123864, 248385, 160185,  21513,  27756, 116784,  33387, 185892,
        52539,  51294, 195741, 149727, 298290, 181749,  95943,  83010,
       127212, 155976, 218097,  28209,  95322,  99699,  54297, 323346,
       240009, 154710,   9000, 251322, 100080,  17169,  78414, 193440,
       175329, 161883,  15000,  16893,  49869,  66798, 118425, 152187,
       183054,   9000, 144192, 122823,  91932, 116808, 184275,  26220,
        64023,  65259, 303807,  31602, 112146,  27723, 145782, 135927,
       131019, 194409, 140475, 122022, 238323, 161901,  85161,  25746,
        43686, 175134, 240105, 102387, 100854, 140565, 172563, 305421,
         9000,  26706,  89085, 238350, 257028,  69669, 196587, 104376,
        15000, 201330, 104547, 181467,  41874,   9000, 179706, 162744,
        38391,  84555, 147156, 199179,  20040,  85824, 247830, 111948,
        37797, 240078,  85413, 165624, 256077, 224994, 308487,  15000,
       271497, 297726,   9000,   9000,  68103, 160071,  29793, 188619,
       144786, 161913, 205257, 308427, 151323, 232842, 235227,  24963,
         9000,  15000, 157794,   5733,  15627,  45480,  76884, 233988,
        90000, 180846,  93546,  38907, 290901, 106764,  48393,  31620,
        95439,  11706,  45522, 212988, 152613,  52866, 315225, 128139,
       136749, 151290,  54051, 235698,   9000,      0, 106965,   9000,
       214911,  89925, 155427, 175545, 204462, 134466, 233022,   9000,
       129768, 201468, 144087,  84027, 208722,  81690, 143502, 208779,
        23163, 164802, 135819, 144312, 118683,  61842,  67857, 141945,
        38478, 118401, 101919,  66771, 292167, 155478, 195960, 159882,
        77574, 105342, 181239, 176670, 122553, 113604, 147684, 182622,
        18504,  82392, 124905,  80598, 178752, 116763,  40296,   9000,
       319470, 128103, 212397,  92595, 269778, 212838, 196320, 121689,
       253272,  70032, 194979,  73758, 115572, 120246,  12927, 126078,
       166488,  42999,  15000,  99585, 175809,  54963,  30423, 177966,
       199413,  28842, 151569,  76341,  72612, 168966,  46809,  82740,
        34656, 146340, 176700, 134631, 206727,  98691,  39039, 182445,
       142377,  48783,  41142,  94677,  10809, 185892, 233445, 225765,
        66198, 137592,  23808,  65220, 117882,  78054, 215556, 159336,
       237618,  94722, 247041,  32001, 155790, 117666,  17157,  40542,
       201177,  16809, 157770, 119184, 182469, 171531, 209502, 115542,
       223266, 143487, 155301,  22599, 171708, 259791, 129456, 181425,
       222174, 293892,  54789,  10029, 260601, 234924, 100008,  90795,
       187245, 200931,  11181, 116757,  66231, 178074,      0, 238233,
       129744,  27795, 155496,  10710, 115773, 129927, 100305, 307320,
        78417, 108654, 168336, 125214, 321990, 114174, 104709,   9000,
       292278, 145083, 252237, 104187, 126429,   9000,  37479, 206052,
       100935,  20130, 108441, 137871,  20529,  48621, 116625, 264636,
        15000,  28947, 204336, 209598,  75774,  17208,   9000, 139566,
         9144, 101826, 169218,   9000,  86298,  83019, 194775,  37533,
       263337, 188136, 130491, 174471,  46719,  36987,  91836, 110592,
        82452, 223680, 103146, 178698,   9000,  47904, 241776,  82545,
        76509,  87402, 288240,  87180,  17865, 185049, 105120, 175632,
       162783,  27057, 260130,  51894,  55197, 189318, 166458,  34947,
       191649, 168537, 110157, 251001, 202065,  23829,  32469,  23709,
         9000, 249114,  14406,  47220, 245955,  58188, 226551, 202467,
        76365, 248931,  22617,   9000, 192609, 241875,  57987,  48345,
       127212, 148620,  61770, 199341, 127575,  82794, 172521, 146973,
        34956, 374274, 194721, 126009,  98925, 161457,  41898, 175737,
       120672, 126435, 174030, 134139, 212658,  73176, 194409,  68814])

In [ ]:
print(first_cibil)

699

Matrix transpose

In [ ]:
transpose_mat=mat.T

In [ ]:
transpose_mat

array([[5.697600e+04, 1.856000e+03, 6.455300e+04, ..., 2.439200e+04,
        6.480300e+04, 2.293800e+04],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 1.133700e+04,
        9.413600e+04, 0.000000e+00],
       [8.031545e+06, 8.993610e+05, 2.387748e+06, ..., 3.012490e+05,
        7.198910e+05, 6.101900e+04],
       ...,
       [7.448610e+05, 0.000000e+00, 2.913766e+06, ..., 1.631635e+06,
        5.000832e+06, 0.000000e+00],
       [3.039100e+04, 1.856000e+03, 2.455700e+04, ..., 2.297700e+04,
        7.237600e+04, 1.610500e+04],
       [1.174700e+01, 4.038100e+01, 3.082000e+00, ..., 7.030000e-01,
        3.770000e-01, 2.220000e-01]])

inverse of matrix

In [ ]:
inverse=np.linalg.inv(mat)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
rank=np.linalg.matrix_rank(mat)

In [ ]:
print(rank)

15

Find Customers Older Than Average

In [ ]:
age=np.array(df['Age'])

In [ ]:
aver=np.mean(age)
print('average age is ',aver)
res=np.array(age>aver)
print(res)

average age is  34.412
[ True  True  True False  True False  True False False  True  True False
  True  True False  True False  True False False False  True  True False
  True False False False False False  True  True  True False False False
  True False False False  True False False  True  True False  True  True
  True  True  True  True False  True  True False False  True  True False
 False  True  True  True  True  True  True False False False False False
 False  True  True False  True False False False False  True  True  True
 False False False False  True  True  True  True  True False  True  True
  True False  True False False  True  True False  True  True  True False
  True  True  True False  True  True False  True  True False  True  True
 False False False False False  True False False False False  True False
 False  True  True False False  True  True False  True  True False False
  True  True  True False  True  True False  True  True False False  True
  True False  True  True False  True  True  True  True  True False  True
  True  True  True  True False False  True  True  True False  True False
 False False False  True  True  True False False  True False False  True
  True  True  True  True  True  True False False  True False False  True
  True  True False  True  True False False  True  True  True  True False
 False False  True False False False False False False  True  True False
  True  True  True  True False False  True False False False False  True
 False  True False  True False False False False  True  True  True  True
 False False False  True  True  True False  True False  True False False
 False False  True False  True  True  True  True  True False False  True
 False  True False False  True  True  True False  True False  True False
 False False False False  True False  True  True  True  True False  True
  True False False False False False False  True  True  True False  True
  True  True False  True False False  True False False  True False False
 False  True  True False  True False False  True  True  True  True False
  True  True  True  True False False False False  True  True False False
  True  True  True  True  True  True  True  True  True False  True  True
  True  True False False  True False False False  True  True  True False
 False False  True  True  True False False False False  True  True  True
 False  True  True  True  True False False  True False False False False
  True False False False False  True  True False  True False  True  True
  True False False  True False  True False False False  True  True  True
 False False False False False False  True  True  True  True False False
  True False False  True  True  True  True False  True False  True  True
 False False  True  True  True False  True  True  True False False False
 False False  True  True  True  True False  True False  True False False
 False False False False False  True False  True  True False  True  True
  True False False  True  True False  True False False False False False
  True False  True  True False False  True  True False False  True False
 False  True  True False False  True  True False False False False False
  True  True  True  True  True False False False False False False False
 False False False False  True False False  True  True False False  True
 False  True  True False False False False  True  True False False False
 False  True False False  True False False False False  True  True  True
 False False  True False  True False False  True False  True False False
 False False False  True  True False False False  True False  True  True
  True  True False  True False False False  True  True False  True False
 False False  True False False False False False False  True  True False
 False False False False  True  True False False  True False  True False
  True  True  True  True  True False  True  True  True False False False
  True False  True  True False False  True  True  True False False  True
 False  True False  True False  True False  True  True  True  True  True
 False False  True  True False False False False  True  True  True False
  True False False  True  True  True False False False False  True  True
 False False False False  True False  True False False False  True False
 False  True  True False  True False False  True  True  True False False
  True  True False  True  True False  True False False False  True  True
  True False  True False False  True  True False False  True False  True
  True False False  True False False False False  True  True  True  True
  True  True  True  True  True False False False False False  True  True
 False False False  True False  True  True  True False  True  True  True
  True  True False False  True False  True False  True False False False
  True False  True False  True False  True  True  True False False  True
 False  True False  True False  True  True  True False False False False
  True  True False  True  True False False False False  True  True  True
  True False False  True  True  True False False False False  True  True
 False  True  True False  True False  True  True False False  True False
 False  True False  True False  True  True False False False  True False
  True False  True False  True False False  True  True False False  True
  True  True False  True  True False False  True  True  True  True  True
  True False  True False False False  True False  True False  True False
  True  True  True  True  True  True  True False False  True False False
  True False  True False False False  True  True  True False  True False
  True  True  True  True False  True False  True  True False  True  True
  True False False False False False  True  True False False  True  True
  True False False False False  True False False False  True  True  True
 False False  True False  True False False  True  True  True  True False
  True False  True False  True  True  True  True  True False  True  True
 False  True False False False False  True  True  True False False False
  True False False  True False  True  True False  True  True  True  True
  True False False False]

Find dot product between:

income vector
asset vector

In [ ]:
asset=np.array(df['Asset_Value'])
income=np.array(df['Applicant_Income'])
dot_prod=np.dot(asset,income)
print(dot_prod)

115006885431768

Find magnitude of income vector.

In [ ]:
magnitude=np.linalg.norm(income)
magnitude

np.float64(1609657.046589428)

Find Column-wise Mean

In [ ]:
average=np.mean(mat,axis=0)
average

array([4.24300570e+04, 9.72711400e+03, 2.21671290e+06, 1.59132000e+02,
       7.23000000e-01, 3.44120000e+01, 6.53013000e+02, 6.25886052e+05,
       1.48118157e+02, 1.81733900e+04, 8.65000000e-01, 1.47000000e-01,
       2.43400000e+00, 1.90804169e+06, 2.36034270e+04, 1.01631030e+01])

In [ ]:
matA = np.array(df[['Applicant_Income', 'Asset_Value']])
matB = np.array(df[['Existing_EMIs', 'Debt_to_Income_Ratio']])
matA
matB

array([[5.6100e+03, 9.8000e-02],
       [9.1660e+03, 4.9390e+00],
       [0.0000e+00, 0.0000e+00],
       ...,
       [3.4514e+04, 9.6600e-01],
       [3.4000e+04, 2.1400e-01],
       [1.5226e+04, 6.6400e-01]])

In [ ]:
addition_mat=matA+matB
addition_mat

array([[6.25860000e+04, 7.44861098e+05],
       [1.10220000e+04, 4.93900000e+00],
       [6.45530000e+04, 2.91376600e+06],
       ...,
       [5.89060000e+04, 1.63163597e+06],
       [9.88030000e+04, 5.00083221e+06],
       [3.81640000e+04, 6.64000000e-01]])

matrix subtraction

In [ ]:
mat_sub=matA-matB
mat_sub

array([[ 5.13660000e+04,  7.44860902e+05],
       [-7.31000000e+03, -4.93900000e+00],
       [ 6.45530000e+04,  2.91376600e+06],
       ...,
       [-1.01220000e+04,  1.63163403e+06],
       [ 3.08030000e+04,  5.00083179e+06],
       [ 7.71200000e+03, -6.64000000e-01]])

matrix multiplication

In [ ]:
mat_multi=np.dot(matA.T,matB)
mat_multi

array([[7.76060727e+11, 1.56940352e+07],
       [3.48109838e+13, 1.96706342e+10]])

row sum of matrix A

In [ ]:
row_sum=np.sum(matA,axis=1)
row_sum

array([ 801837,    1856, 2978319, 3576694,  481718, 1438867, 2149986,
        662552,  591908, 2875991, 1640927, 1291966, 1359211, 1828572,
        941299, 4882838, 1227390, 1234875, 2007073, 3221879, 1680947,
        958196, 5464830, 3578941, 1631012, 1765108,  171034,  859022,
       1514036, 1683242, 4151458,  673395, 3898884, 1552269, 1595917,
       1344342, 1563453,  798045, 1128727, 4380659,   90189, 2774064,
       1467783, 1979182, 3067750, 1327006, 1440142, 2167109, 4291272,
        960463, 2904259,  649718, 3536053, 4705535, 2266504,  286652,
       2069423, 1507967, 7121579,  926007, 5726072, 1834729, 2076308,
       1825393, 4549352,  476909, 4187035, 1923366,  930411, 2502969,
        709376,    5000, 3029943, 4312223, 2065668, 1200505, 1673839,
       1583787,  631491,  132577, 2965390, 3901931,  452586,    3000,
       1634387,  565960, 2425939, 3753451,  607290, 3504573, 2812124,
        281512,  781136, 1744568, 2844886,  624551, 3033215, 3807247,
       2286076,    3000, 3370408, 5628121, 1243816,  222352, 3726214,
       4637029, 3467695, 3332460,    7781, 5207625, 3080771, 3504293,
        324548, 5115250,    5000, 2690301, 3352477, 5191189, 2476365,
       3570747,    3000, 1391686,    6348, 2028071,  514670, 1894989,
       2179116,  424988,  662295, 4461912, 2485312, 1129516,  724755,
       1382871, 1408439, 2864251,    4891, 2726119, 1259858,  801825,
        984419, 2190723,  491652, 5532061, 1606679, 3878419, 2738847,
       1817830, 2202564, 6789498, 1178821,  909575, 4958499, 2996647,
       6305137, 1767655, 2829900, 1074585,    3345,  547743, 3106886,
       1092458,  559278, 1669536, 2451325, 1571415,    9510, 2664287,
        238287, 1980019, 1952975, 3317213, 1003785,  292447,  684727,
       2171693, 3312115, 1238817, 5172196, 1589686,  959048, 2523595,
       1956371, 1942361,  700439, 2374937, 2923527, 1630309, 1575876,
       1661496, 1427634, 1699159,  203748, 3548083, 2055965, 3484238,
       2695703, 4177182, 1763802, 5299741, 1148323, 3378249,  681824,
        730132,    3000, 1325798, 2772109, 2990377, 1433219, 2971132,
       4106336, 2039955,  837615, 5068570, 2121625, 1941091,  462474,
       2533806, 1866035, 2028824, 2213467, 1464687, 1745335, 4544560,
       1926612, 1295676, 3359234, 3003232, 3390552,    3000, 1856712,
       4318051, 2448532, 4165738, 3899102, 4421991, 2883095, 1214759,
        304441, 1264310, 1130089, 1679195,  487305, 1855733,  586572,
       1539832, 2544924, 1627200,  355083, 2743166, 3889864,  707320,
        974016, 1080911, 1977203, 3635542, 1356676,    3000, 2834989,
        148760, 1625718, 2751998,  324186, 5046016, 1532873,  193752,
       1729154, 1312802, 1315020,    5000, 1164536, 1313876, 2228616,
        490368,  201184, 1910428,  396310, 2944661,       0,   18405,
       3414869, 1254111,  623000, 5222513, 3207114,  659277,    6877,
          3423, 2546669, 4296765,       0,    5036, 1884403, 1974140,
       2932231, 1735108,  993852, 2248277,   47642,   21143,  386517,
        369784, 1534076,  687561,  981446,  120378, 2981132,    3000,
       4324009, 1426924, 1855745, 1785230, 2432786, 2025600, 3201987,
       1577987, 2965290, 2591967, 1007184,  942633,  491089,  736858,
        823826,  540522,  489207, 1633078,  733095, 1086944,  256841,
       3327431, 2447107,  616249, 2968576,  664133, 5179903, 2532546,
       3116322,  790905, 3219338, 1757197, 3250925, 2319492, 2701200,
       3466917, 1683399,  166359,  796384, 1400654, 1719647, 3216052,
        447365,  145912, 2318020, 1977098,  320213,  959607,  927001,
        202736,  381823, 1171496, 1495141,   12088,  813140,    3713,
         12895,  361705,  343012, 2951058, 1386474, 5531626, 1231085,
       2768988, 4594721, 4642839, 1799391, 5194704,  169582, 1647491,
       1631708,  545746, 1966918, 4054102, 1252783, 4344634, 2529382,
       1479251, 2420464, 1094832, 3529464, 2738938, 4030020, 4983586,
        496416, 2617762, 3704413, 5738545, 2623003, 5008239, 1368691,
       4914558,  750976, 2832483, 2629182, 3059987, 1500426,  120498,
       2521527, 1141399, 1846624,  680483, 2986492, 1336334,  319526,
        716980,  120236,       0, 1012249, 2056384, 1365349, 3163567,
        365372, 2992319, 1012379, 2147283, 2261737, 1291169, 2182303,
       2814376,  745672, 2636305, 2584208, 1150110, 2950129, 2099900,
       3098393, 2485919, 1849215, 3264284, 1768899,  745430, 2365157,
       3637904,  113185, 1042599, 1020022,  284139,  192855,    2428,
        616244, 1876708,  762961,  638908, 1553308,  483259, 4641401,
       1930186, 1604749, 1610839,    7918, 1574313, 1299151, 1312106,
       5994449, 1836476, 4934061, 2373646,       0, 1545907, 4107899,
       4246720, 2671423, 1077059, 4285027, 1790411,  576847, 5841432,
       2153929,  675301, 2016486,  262120, 3015355,  454467,  675500,
        735206, 1703447,    3000, 3730960,  662438, 3163751, 1309852,
       3120142,  534762,  371353, 1814092, 2047733,  668004, 3799010,
       6411694,  793672,  408567, 1921034, 1737303, 2201291, 1043111,
        743880, 1941054, 6781487, 2383722, 1113187, 2443475,  339002,
          5000, 5054647, 1892093, 1034545, 3174031, 2044788, 1379574,
       7079091, 2497547,  235711, 1107058, 1564970, 1663707,  506807,
       2384337, 1904626, 3794153, 2085830,  859725, 2350257,  746386,
        866454,   17137, 1118269, 1535379, 1879058,    3229,   66870,
       1914978, 1060367,  771076, 1541276, 2231664, 2648355, 1546439,
        435546, 1438144, 1047402, 2207477, 1736868, 6473652,  466092,
       3009284,  952560,  962693, 3010717, 4711033,   74503, 7823026,
        704144, 2503748,  906385, 1582762, 4241320, 1730467,  416510,
         19490,  360222,  918153, 1091386, 2913204,    3000, 2294955,
       2245325,   26808, 3752769, 2973096, 1566912, 1175019,    9252,
       2462497,  261515, 1421321,  667658,  263469, 1961029, 1251753,
       4896431, 2463517, 1311269, 2556527, 1814761, 1551302, 2195488,
         27716, 1943592,  578900, 1317856, 4625317, 3884657, 1702038,
          3000, 5382647, 1486851,  511540, 1493395, 5119570, 4158068,
       2227171,    5000,    5631,  409460,  910231, 2092476, 1723290,
       2898092,  386053, 3104570, 2054469,  942146,  787365, 4285515,
        781347,  583353,  587478, 5016725,  680771, 1222961,  681069,
       2869267, 1623702,  677381, 2540146, 3899427, 1901176, 3413227,
       2715261, 1659790, 1049634,  397486, 1582283, 3071052, 2820160,
       1705948, 2297123, 3086938, 4360384,  702447,  373436, 2235611,
       2612362, 3437335,  496524, 3132288,  564604,    5000, 1956500,
       1568005, 2836707,  185702,  363077, 2745014, 2155182,   12797,
       1307299, 3962125, 2861689,  550759, 1280356, 5454208, 1810918,
        225983, 3226600, 1905482, 3948912, 2953946, 3323635, 7811444,
        184023, 3429712, 3560817,    3000,    3000, 1352898, 2020979,
          9931, 1918861, 1725558, 3324563, 2584340, 5663943, 2476169,
       6213190, 3082682,    8321,    3000,  316470, 3370677,  380266,
          5209, 1034697, 1503813, 3097603, 1024131, 1930263, 2990104,
        760090, 3032859, 1303030,  715964,  657195, 1432832,  186631,
       1125624, 1976385, 1219940,  574050, 4373510, 2334164, 1227061,
       1713877, 1375416, 3238551,  680339,       0, 2795763,  213592,
       2127526, 2274788, 2120007, 3538149, 5541576, 1675798, 4033724,
        989801, 2813178, 2494388, 1237747,  568413, 4661527,  630630,
       2405493, 2678382, 1232403, 4831390, 2406744, 1210996, 1390454,
       1480702,  717543, 1812940,  136379, 1673362, 1590692,  986298,
       3609887, 2361203, 2555345, 4356469, 1522527, 1979103, 2869047,
       1861553, 2126986, 1356676, 3598671, 2114956,    6168, 1408617,
       2039198,  348143, 1642071, 1083648,  776263,  526928, 2616011,
       3072201, 2251498, 1258043, 2413664, 2550284, 5437449, 1772738,
       6225207, 1212043, 1868370, 1915264, 1264378, 2194706,  270021,
       1371030, 2668594, 1143460,   28338, 1681804, 2794842, 1383632,
        302031, 1604019, 1674364,  486506, 2076517, 1961463,  779860,
       2104866, 1125481, 1492628, 1014542, 2862745, 4200663, 2534100,
       6155343,  596468,  302167, 4452741, 1521093,  298080,  621746,
        597069,    3603, 2252572, 2985917, 3125404,  343172, 1962927,
          7936,  866598, 1005643, 1748649, 4726528, 2933975, 2760401,
       1235691, 5966416,  186287, 1579305, 1113358,   11820, 1222373,
       2089773,    5603, 2373477, 3087105, 4529346, 1915607, 1673414,
       1804102, 5056175, 1399554, 4829972,  913162, 2133020, 5379222,
       1773320, 2033868, 3411259, 3962000, 1205344,  515411, 3350536,
       4788307, 1436783, 1489640, 3370217, 2674422,  715016, 1314666,
        663861, 3258241,       0, 6329042, 1860228,  323638, 1655337,
          3570, 2293274, 1572301,  748992, 6522242, 1385012, 1022412,
       3416456, 1572839, 4947643, 2854096, 1691650,  163378, 4545891,
       2645039, 5797284, 1860913, 1814038, 1003662,  108650, 2260697,
        940407,  657012, 2235560, 1875217,  315856,  436304, 1341602,
       3202210,    5000,  704695, 2957190, 2997695,  619118,    5736,
          3000, 1098051,    3048, 1659571, 2185466,  117601, 2213562,
         27673, 2208804,   12511, 3796578, 5585676, 2010284, 2933253,
       1140097, 1309702,  230342, 1375119, 2023632, 3081760, 2725764,
       3915757,  268440,   15968, 2448088, 1129031,  567232,  941846,
       5516748,  156400,    5955, 4083083, 1183923, 2151271, 1909909,
        630039, 3463101,  894047, 1032666, 5395050, 2571744, 1163999,
       2510338, 3895541, 1533381, 5966099, 2378098,  852975, 1183361,
        973262,   42938, 2703618,  570597,   15740, 5688280, 1259550,
       7441098, 2086359, 1442560, 2955249,    7539,    3000, 2643362,
       2764456,  536006,  392848, 1584930, 1649010,  214527, 2302335,
       2170666, 1029414, 1951532, 3044739,  778970, 5223488, 1769375,
       1595101, 2042561, 4848910,   13966, 2507562, 1959512, 1218897,
       2748573, 1940251, 2484855, 1656027, 5065635,   22938])